version: "2"

run:
  timeout: 3m

linters:
  default: standard
  enable:
    - gocritic
    - misspell
    - unconvert
    - unparam
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
    misspell:
      locale: US
  exclusions:
    presets:
      - comments
      - std-error-handling
      - common-false-positives
    rules:
      - path: _test\.go
        linters:
          - gocritic
          - unparam

formatters:
  enable:
    - gofmt
    - goimports
